### ISSUE TITLE
Kendi kendini trollere ekleme

### ISSUE THREAD

**Issue by kyzn** [expeditor/eksi-reaktor#4]
Kullanıcı kendi entryleri altında troll düğmesini görebiliyor, hatta tıklayıp "engellendi" bilgisini de görebiliyor. Ancak tabii ki böyle bir şey gerçekleşmiyor. Vakit bulunca bunun bir pull request hazırlayabilirim.

**Comment by expeditor** [comment]
Bence buna ihtiyaç yok ama yine de bir güncelleme arasında halledeyim. Araştır kolonu profil sayfalarında, olay sayfalarında da çıkması ile ilgili düzeltmeler yapacağım, o sırada basit bir if ile hallederim.
